name: deploy-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

env:
  BASE_URL: /${{ github.event.repository.name }}

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production
# deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Set up Go stable
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          go install github.com/gopherdata/gophernotes@v0.7.5
          find ~ -name kernels
          mkdir -p ~/.local/share/jupyter/kernels/gophernotes
          cd ~/.local/share/jupyter/kernels/gophernotes
          cp "$(go env GOPATH)"/pkg/mod/github.com/gopherdata/gophernotes@v0.7.5/kernel/*  "."
          chmod +w ./kernel.json # in case copied kernel.json has no write permission
          sed "s|gophernotes|$(go env GOPATH)/bin/gophernotes|" < kernel.json.in > kernel.json

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build libro

      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: libro/_build/html

      # Deploy the book's HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
